### ISSUE TITLE
convert2HTML: labelling of unnumbered msItems

### ISSUE THREAD

**Issue by holfordm** [bodleian/consolidated-tei-schema#15]
If a msItem (numbered with `@n`) contains other msItems, which do not have `@n`, it seems that lettering is introduced automatically, but it does not seem to increment past 'a'. 
See http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_317 for an example. 
Is this due to an issue in convert2HTML, or somewhere else, that can be fixed, or is it a data issue that needs attention in the TEI?

**Comment by andrew-morrison** [comment]
This is not a data issue, it is a bug in the XSL. In doesn't even have anything to do with numbering. The XSL will only add numbering if the msItem has a `@n` attribute.

What happened is I accidentally added an 'a' while working on something completely unrelated a week ago. It is completely random that it was in the template for nested msItems. That was probably just where the cursor happened to be when I pressed Ctrl+F and started typing, and if you do that too quickly Oxygen will insert the first character into the editor rather than the search interface. I should've spotted it in the diff view when committing, but didn't. Apologies.

**Comment by andrew-morrison** [comment]
Fix committed. If you re-index it will remove the a's.
