### ISSUE TITLE
Rename Schema

### ISSUE THREAD

**Issue by ahankinson** [bodleian/consolidated-tei-schema#2]
The 'bodley' part of the schema name reduces the likelihood that this can be used with projects outside of the Bodleian.

This schema should thus be renamed to reflect the wider nature of its application; perhaps rename it to 'ms-desc.(odd | rng)'?

Issue raised by @eifionjones.

**Comment by ahankinson** [comment]
Or perhaps 'consolidated-msdesc-schema.odd'?

**Comment by eifionjones** [comment]
Either would be fine for me!

**Comment by andrew-morrison** [comment]
Sorry it has taken me a while to get round to this. I'm still getting used to the various repositories and getting a feel for what's meant to be there and what probably should be tidied up.

This renaming is a "branding" issue, of sorts, so I guess the main thing is to rename the consolidated-tei-schema versions and search and replace all the xml-model PIs in all the Fihrist TEI XML files. But there are also copies of schemas elsewhere, such as...

https://github.com/bodleian/fihrist-mss/blob/master/bodley-msDesc.rng
https://github.com/bodleian/medieval-mss/blob/master/collections/bodley-msDesc.rng

...the former isn't used. The latter is referenced in xml-model PIs in all the Medieval TEI XML files, as a relative path. Should these be deleted and everything pointed to the renamed consolidated-tei-schema versions? All copies are currently identical.

**Comment by ahankinson** [comment]
I would like to seem them updated to the new version -- @eifionjones , @holfordm : Would you be ok if we updated your files to point to a new schema?

**Comment by eifionjones** [comment]
Yep, fine with me!

**Comment by holfordm** [comment]
This seems to have lost the schematron rules that I added for the medieval catalogue. They seem to be in a separate branch that hasn't been merged https://github.com/bodleian/consolidated-tei-schema/blob/medieval-schematron/bodley-msDesc.odd 
(the first rule is not just for the medieval catalogue btw: it checks that the xmlid matches the filename, which is essential for the HTML and indexing processed.)
@andrew-morrison  can you merge the different branches, or feel free to adjust the schematron rules as necessary? 
I won't be doing any work on the catalogue this Friday the 26th, so that would be a good time to for you to update the medieval files - thanks.

**Comment by andrew-morrison** [comment]
OK, I'll merge the changes in that Medieval branch into the master here and update the Medieval files on Friday.

**Comment by andrew-morrison** [comment]
@holfordm: I've batch converted all Medieval TEI files to use the new schema name and master copy here on GitHub, the same now as Fihrist. Sorry, I haven't had time to merge the two versions of the .odd file, I'll do that next week.
